### ISSUE TITLE
CraftCMS 4

### ISSUE THREAD

**Issue by mmc501** [boscho87/serve-secret#11]
Will this plugin be updated for CraftCMS 4?

**Comment by boscho87** [comment]
@mmc501 
Yeah i think this should not be a lot of work.

**Comment by boscho87** [comment]
hey @mmc501 are you able to tests the craft 4 branch (or if its easier for you if i crate a tag) -> its acually not well tested

**Comment by boscho87** [comment]
craft 4 support should now work properly hope you can use the plugin. no changes needed after the Update!

use version 2.0.0 of the plugin for craft4!
