### ISSUE TITLE
the file you looking for could not be found by servesecret plugin

### ISSUE THREAD

**Issue by EternalBlack** [boscho87/serve-secret#2]
I just tried your plugin. I unfortunately ran into the following error immediately:

> Internal Server Error
> the file you looking for could not be found by servesecret plugin.

I used `<a href="{{ secretFile(entry.oneTimeDownload.one()) }}">{{ entry.oneTimeDownload.one().title }}</a>` where `entry.oneTimeDownload.one().title` itself is accessible. and printed correctly. 

Volume is set up like this:

> Name
> `Secret Files`
> 
> Handle
> `secretFiles`
> 
> Assets in this volume have public URLs
> `False`
> 
> Volume Type
> `Local folder`
> 
> File System Path
> `@webroot/../assetVolumes/secret`

**Comment by boscho87** [comment]
do you have tried it with the whole system path?
correct file permission
maybe do you have some special chars ?

i will  maka some tests tomorrow

**Comment by EternalBlack** [comment]
The image renders just fine without the plugin (i.e. it can be resolved in an `<img>` tag), so permissions seem to be correct. The filename is `IMG_4793.JPG` don't know if this could be a potential problem.
Plugin was installed via the Pluginstore of Craft itself, is this could be an issue.

Deutsch:
Also das Bild lädt ganz normal, wenn ich es in einem <img> Tag einbette. Wenn ich versuche es über das Plugin als download (`<a>`) auszugeben klappt es leider nicht. Der Dateiname des Bildes ist `IMG_4793.JPG` wobei ich nicht weiß, ob das ein mögliches Problem ist.

Installiert ist das Plugin über den Pluginstore von Craft, falls das noch wichtig ist.
LG

**Comment by boscho87** [comment]
This issue should be resolved, please verify it.

Habe das Problem behoben, bitte bestätigen wenn ok.

`composer update` should do the job. 

@EternalBlack i also added an additional parameter to the twig extension 

```twig
#inline the file / download the file --> false for download
<a href="{{ secretFile(entry.files.first(),false) }}">{{entry.files.first().title}}</a>

{% for files in entry.files %}
       <a href="{{ secretFile(file,true) }}">file.title</a>
{% endfor %}

```

**Comment by EternalBlack** [comment]
Thank you for the fast support! Unfortunately my Craft install doesn't see the plugin update just yet. It's still `v1.1.0`

**Comment by boscho87** [comment]
must be an issue on your environment... are you able to execute `composer update` in the command line?

maybe you need to change composer.json  before you execute the update
```composer
"require": {
 "itscoding/serve-secret": "^1.0.0"` 
   ...
}
```

**Comment by boscho87** [comment]
okay was a problem with composer (packagist.org) ... now its @ version 1.2.0 .. this should work now

**Comment by EternalBlack** [comment]
Works like a charm now! Thank you very much!

**Comment by boscho87** [comment]
thanks for reporting :+1:
