### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Justinomics** [boscho87/serve-secret#5]
## Description
I encounter an internal server error whenever I try to download an asset, any ideas as to why that might be? I've tried both methods from the instructions.

**Internal Server Error**
the file you looking for could not be found by servesecret plugin

The URL for the error looks like https://mydomain.com/actions/serve-secret/file-serve/get-secret-file?file_path=dlNZOGtpcWY ... [ lots more encrypted text here ] ... p3PT0%3D&file_hash=YWFiMTU5N ... [ more encrypted text here ] ...wMDc5YjY%3D&file_inline=0

## Expected behavior
The file should download.

**Comment by Justinomics** [comment]
I believe it was a path issue!

**Comment by boscho87** [comment]
@justinpyvis 

there was a bug when you put files into subfolders:

https://github.com/boscho87/serve-secret/commit/84c565b49fe04befd5df344ec6282452f5994e89#diff-2c05ab546421ad1d54dfbaa87ee46a2e

when you should update your plugin
