### ISSUE TITLE
In .env defined aliases don't work 

### ISSUE THREAD

**Issue by shannonschaerer** [boscho87/serve-secret#8]
**Describe the bug**
If other aliases are used to define path to the volume’s directory on the file system, plugin can't find file.

**To Reproduce**
1. Go to 'Settings > Assets > Volumes'
2. Click on 'whichever secret volume'
3. Input path in 'File System Path', i.e. @basePath
4. In front end click on any file which would be in secret volume.
5. Error: File Exception – craft\errors\FileException - the file you looking for could not be found by servesecret plugin

**Expected behavior**
File should open.

**Comment by boscho87** [comment]
The solution is to replace this 

https://github.com/boscho87/serve-secret/blob/master/src/services/Security.php#L80

With something like: https://craftcms.stackexchange.com/a/26121/5735 

If someone like, create a Pull Request with this fix.

**Comment by boscho87** [comment]
@shannonschaerer should be fixed now (for craft 4 version of the plugin)
